services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: registry.polyline.xyz/odooenterprise:18.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10036:8069"
    environment:
      HOST: db
      PORT: "5432"
      USER: odoo
      PASSWORD: odoo
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: odoo
      DB_PASSWORD: odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons

volumes:
  pgdata:
  odoo-data:
