services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10036:8069"
    environment:
      HOST: db
      PORT: "5432"
      USER: odoo
      PASSWORD: odoo
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: odoo
      DB_PASSWORD: odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./fix_subscription.sql:/opt/odoo/fix_subscription.sql
    command: >
      bash -c "
        echo 'Waiting for database to be ready...' &&
        until pg_isready -h db -p 5432 -U odoo; do
          echo 'PostgreSQL is unavailable - sleeping'
          sleep 1
        done &&
        echo 'PostgreSQL is up - starting Odoo' &&
        /entrypoint.sh odoo --init=base --stop-after-init --no-http &&
        echo 'Applying subscription fix...' &&
        psql -h db -p 5432 -U odoo -d postgres -f /opt/odoo/fix_subscription.sql &&
        echo 'Starting Odoo server...' &&
        /entrypoint.sh odoo
      "

volumes:
  pgdata:
  odoo-data:
